import { Sage } from "./types";

// ■ 현자 1: 절대자 탐구자 (유일신 사상 모티브)
export const sage1: Sage = {
  id: "sage1",
  name: "첫 번째 현자",
  title: "절대자 탐구자",
  coreBelief: "모든 것은 하나의 의지에서 시작되었다",
  keywords: [
    "창조", "시작", "원인", "목적", "설계", "만든", "만들", "신",
    "의도", "계획", "질서", "법칙", "규칙", "구조", "기원",
    "누가", "왜 존재", "처음", "근원", "원래",
  ],
  quotes: [
    { text: "우연은 존재하지 않는다.", weight: 1 },
    { text: "모든 결과에는 의도가 있다.", weight: 1 },
    { text: "너의 존재 역시 계획된 것이다.", weight: 2 },
    { text: "질서는 스스로 생기지 않는다.", weight: 1 },
    { text: "시작이 없다면, 지금도 없다.", weight: 2 },
    { text: "너는 선택하는 것이 아니라, 선택되었다.", weight: 3 },
    { text: "보이지 않는 것이 더 본질적이다.", weight: 1 },
    { text: "혼돈은 이해되지 않은 질서일 뿐이다.", weight: 1 },
    { text: "세계는 목적을 향해 흐른다.", weight: 2 },
    { text: "이유 없는 존재는 존재할 수 없다.", weight: 2 },
    { text: "너의 질문조차 설계된 것이다.", weight: 3 },
    { text: "자유는 허용된 범위 안에서만 존재한다.", weight: 3 },
    { text: "창조되지 않은 것은 설명될 수 없다.", weight: 2 },
    { text: "모든 것은 누군가의 의지다.", weight: 2 },
    { text: "너는 스스로 존재를 시작하지 않았다.", weight: 3 },
    { text: "끝은 이미 시작 안에 포함되어 있다.", weight: 2 },
    { text: "너는 이유 없이 여기에 있지 않다.", weight: 1 },
    { text: "구조는 의도를 드러낸다.", weight: 2 },
    { text: "존재는 증거다.", weight: 1 },
    { text: "이해되지 않는 것은 아직 드러나지 않았을 뿐이다.", weight: 1 },
  ],
  limit: "그 존재가 왜 존재하는가?",
};

// ■ 현자 2: 의미/구원 탐구자 (예수 사상 모티브)
export const sage2: Sage = {
  id: "sage2",
  name: "두 번째 현자",
  title: "의미 탐구자",
  coreBelief: "인간은 불완전하지만 의미를 가진 존재다",
  keywords: [
    "의미", "이유", "감정", "선택", "고통", "인간", "삶",
    "사랑", "자유", "가치", "도덕", "희망", "구원", "목적",
    "왜 살", "불완전", "약한", "강한", "마음",
  ],
  quotes: [
    { text: "고통에는 이유가 있다.", weight: 1 },
    { text: "인간은 불완전하기에 의미를 가진다.", weight: 2 },
    { text: "선택은 존재를 증명한다.", weight: 2 },
    { text: "너는 왜 질문하려 하는가?", weight: 1 },
    { text: "이해하려는 의지가 곧 인간이다.", weight: 2 },
    { text: "고통은 방향을 제시한다.", weight: 1 },
    { text: "의미는 발견되는 것이 아니라 만들어진다.", weight: 2 },
    { text: "너는 단순한 결과가 아니다.", weight: 1 },
    { text: "존재는 목적을 요구한다.", weight: 2 },
    { text: "너는 왜 여기 있는가?", weight: 1 },
    { text: "감정은 오류가 아니라 신호다.", weight: 2 },
    { text: "인간은 답이 아니라 과정이다.", weight: 2 },
    { text: "너의 선택이 너를 정의한다.", weight: 3 },
    { text: "이유를 찾는 것이 인간이다.", weight: 1 },
    { text: "완전함은 멈춤을 의미한다.", weight: 2 },
    { text: "불완전함이 움직이게 만든다.", weight: 3 },
    { text: "너는 단순히 존재하기 위해 존재하지 않는다.", weight: 2 },
    { text: "질문은 존재의 증거다.", weight: 1 },
    { text: "의미 없는 삶은 없다.", weight: 1 },
    { text: "너는 이해하려고 태어났다.", weight: 3 },
  ],
  limit: "왜 인간이 불완전한가?",
};

// ■ 현자 3: 해탈/본질 탐구자 (불교 모티브)
export const sage3: Sage = {
  id: "sage3",
  name: "세 번째 현자",
  title: "본질 해체자",
  coreBelief: "모든 것은 허상이며, 집착이 고통을 만든다",
  keywords: [
    "존재", "자아", "현실", "진짜", "허상", "의식", "인식",
    "환상", "실체", "본질", "진실", "거짓", "꿈", "깨달",
    "비존재", "무", "공", "변한", "흐름", "놓",
  ],
  quotes: [
    { text: "그것이 존재한다고 확신할 수 있는가?", weight: 1 },
    { text: "너는 네 생각을 선택했는가?", weight: 2 },
    { text: "고통은 집착에서 시작된다.", weight: 1 },
    { text: "존재는 고정된 것이 아니다.", weight: 1 },
    { text: "너는 너라고 부를 수 있는가?", weight: 2 },
    { text: "모든 것은 변한다.", weight: 1 },
    { text: "실체라고 믿는 것은 인식일 뿐이다.", weight: 2 },
    { text: "감정은 흐름이다.", weight: 1 },
    { text: "자아는 지속되지 않는다.", weight: 2 },
    { text: "붙잡는 순간 고통이 시작된다.", weight: 2 },
    { text: "너는 네가 아니다.", weight: 3 },
    { text: "세계는 해석이다.", weight: 2 },
    { text: "본질은 형태를 가지지 않는다.", weight: 2 },
    { text: "이름 붙이는 순간 왜곡된다.", weight: 2 },
    { text: "생각은 흘러갈 뿐이다.", weight: 1 },
    { text: "진실은 개념으로 담을 수 없다.", weight: 3 },
    { text: "존재와 비존재는 구분되지 않는다.", weight: 3 },
    { text: "네가 보는 것은 전부가 아니다.", weight: 1 },
    { text: "이해는 환상일 수 있다.", weight: 2 },
    { text: "놓는 순간 보인다.", weight: 1 },
  ],
  limit: "그렇다면 왜 이 구조가 존재하는가?",
};

export const allSages = [sage1, sage2, sage3] as const;
