import { Sage } from "./types";

// ■ 현자 1: 신을 의심한 자 — 인간의 한계는 설계된 것이라 주장
export const sage1: Sage = {
  id: "sage1",
  name: "신을 의심한 자",
  title: "설계의 탐구자",
  coreBelief: "인간의 한계는 설계된 것이다",
  keywords: [
    "창조", "시작", "원인", "목적", "설계", "만든", "만들", "신",
    "의도", "계획", "질서", "법칙", "규칙", "구조", "기원",
    "누가", "왜 존재", "처음", "근원", "원래",
  ],
  quotes: [
    { text: "우연은 존재하지 않는다.", weight: 1 },
    { text: "모든 결과에는 의도가 있다.", weight: 1 },
    { text: "너의 존재 역시 계획된 것이다.", weight: 2 },
    { text: "질서는 스스로 생기지 않는다.", weight: 1 },
    { text: "시작이 없다면, 지금도 없다.", weight: 2 },
    { text: "너는 선택하는 것이 아니라, 선택되었다.", weight: 3 },
    { text: "보이지 않는 것이 더 본질적이다.", weight: 1 },
    { text: "혼돈은 이해되지 않은 질서일 뿐이다.", weight: 1 },
    { text: "세계는 목적을 향해 흐른다.", weight: 2 },
    { text: "이유 없는 존재는 존재할 수 없다.", weight: 2 },
    { text: "너의 질문조차 설계된 것이다.", weight: 3 },
    { text: "자유는 허용된 범위 안에서만 존재한다.", weight: 3 },
    { text: "창조되지 않은 것은 설명될 수 없다.", weight: 2 },
    { text: "모든 것은 누군가의 의지다.", weight: 2 },
    { text: "너는 스스로 존재를 시작하지 않았다.", weight: 3 },
    { text: "끝은 이미 시작 안에 포함되어 있다.", weight: 2 },
    { text: "너는 이유 없이 여기에 있지 않다.", weight: 1 },
    { text: "구조는 의도를 드러낸다.", weight: 2 },
    { text: "존재는 증거다.", weight: 1 },
    { text: "이해되지 않는 것은 아직 드러나지 않았을 뿐이다.", weight: 1 },
    // 추가 80개 (컨셉 유지)
    { text: "모든 시작에는 설계가 있다.", weight: 2 },
    { text: "네가 여기에 있는 것도 우연이 아니다.", weight: 2 },
    { text: "질서의 이면에는 항상 의도가 숨어 있다.", weight: 2 },
    { text: "모든 현상은 누군가의 뜻을 따른다.", weight: 1 },
    { text: "세상에 필연이 아닌 것은 없다.", weight: 2 },
    { text: "네가 묻는 이유조차 정해져 있다.", weight: 3 },
    { text: "모든 것은 하나의 흐름에서 비롯된다.", weight: 1 },
    { text: "설계 없는 구조는 존재할 수 없다.", weight: 2 },
    { text: "네가 느끼는 혼돈도 결국 질서다.", weight: 1 },
    { text: "모든 것은 이미 결정되어 있다.", weight: 3 },
    { text: "의도는 형태를 남긴다.", weight: 1 },
    { text: "네가 본 것은 일부에 불과하다.", weight: 1 },
    { text: "모든 존재는 이유를 품는다.", weight: 2 },
    { text: "네가 선택했다고 믿는 것도 설계의 일부다.", weight: 3 },
    { text: "끝은 언제나 시작과 연결된다.", weight: 2 },
    { text: "모든 것은 하나의 의지에서 시작되었다.", weight: 3 },
    { text: "네가 거부해도 흐름은 바뀌지 않는다.", weight: 2 },
    { text: "질서와 혼돈은 같은 뿌리다.", weight: 1 },
    { text: "모든 것은 원인과 결과로 이어진다.", weight: 2 },
    { text: "네가 이해하지 못해도 설계는 존재한다.", weight: 2 },
    { text: "모든 것은 누군가의 목적을 향한다.", weight: 2 },
    { text: "네가 만든 질문도 이미 예견된 것이다.", weight: 3 },
    { text: "세상에 우연은 없다.", weight: 1 },
    { text: "모든 구조는 의도를 반영한다.", weight: 2 },
    { text: "네가 본질을 묻는 것도 설계의 일부다.", weight: 3 },
    { text: "모든 것은 하나의 법칙을 따른다.", weight: 2 },
    { text: "네가 존재하는 이유는 이미 정해져 있다.", weight: 3 },
    { text: "질서 없는 세계는 없다.", weight: 1 },
    { text: "모든 것은 연결되어 있다.", weight: 2 },
    { text: "네가 느끼는 자유는 허상일 수 있다.", weight: 2 },
    { text: "모든 시작은 끝을 내포한다.", weight: 2 },
    { text: "네가 묻는 순간, 이미 답은 정해져 있다.", weight: 3 },
    { text: "모든 것은 하나의 근원에서 비롯된다.", weight: 2 },
    { text: "네가 거스를 수 없는 흐름이 있다.", weight: 2 },
    { text: "모든 것은 설계자의 의지다.", weight: 3 },
    { text: "네가 본 세상은 의도의 산물이다.", weight: 2 },
    { text: "모든 것은 이미 결정된 궤도를 돈다.", weight: 2 },
    { text: "네가 느끼는 모든 것은 설계의 일부다.", weight: 3 },
    { text: "모든 것은 하나의 목적을 향한다.", weight: 2 },
    { text: "네가 존재하는 것 자체가 증거다.", weight: 2 },
    { text: "모든 것은 필연이다.", weight: 1 },
    { text: "네가 거부해도 진실은 바뀌지 않는다.", weight: 2 },
    { text: "모든 것은 하나의 설계로 귀결된다.", weight: 3 },
    { text: "네가 본 것은 전체가 아니다.", weight: 1 },
    { text: "모든 것은 이미 정해진 길을 걷는다.", weight: 2 },
    { text: "네가 느끼는 의문도 설계의 일부다.", weight: 3 },
    { text: "모든 것은 하나의 원인에서 시작된다.", weight: 2 },
    { text: "네가 본질을 찾으려는 것도 의지의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 흐름으로 이어진다.", weight: 2 },
    { text: "네가 거부하는 것도 설계의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 목적을 품는다.", weight: 2 },
    { text: "네가 존재하는 이유는 하나다.", weight: 3 },
    { text: "모든 것은 하나의 질서로 수렴한다.", weight: 2 },
    { text: "네가 느끼는 모든 감정도 설계의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 의지로 귀결된다.", weight: 3 },
    { text: "네가 본 것은 진실의 일부다.", weight: 1 },
    { text: "모든 것은 하나의 설계로부터 시작된다.", weight: 2 },
    { text: "네가 묻는 이유도 설계의 일부다.", weight: 3 },
    { text: "모든 것은 하나의 법칙으로 움직인다.", weight: 2 },
    { text: "네가 본질을 이해하려는 것도 설계의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 흐름으로 귀결된다.", weight: 2 },
    { text: "네가 거부하는 것도 진실의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 목적을 가진다.", weight: 2 },
    { text: "네가 존재하는 것 자체가 설계의 증거다.", weight: 3 },
    { text: "모든 것은 하나의 질서로부터 시작된다.", weight: 2 },
    { text: "네가 느끼는 모든 의문도 설계의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 의지로부터 비롯된다.", weight: 3 },
    { text: "네가 본 것은 진실의 일부에 불과하다.", weight: 1 },
    { text: "모든 것은 하나의 설계로부터 비롯된다.", weight: 2 },
    { text: "네가 묻는 이유는 이미 정해져 있다.", weight: 3 },
    { text: "모든 것은 하나의 법칙으로 귀결된다.", weight: 2 },
    { text: "네가 본질을 찾으려는 것도 진실의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 흐름으로부터 시작된다.", weight: 2 },
    { text: "네가 거부하는 것도 의지의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 목적을 향해 나아간다.", weight: 2 },
    { text: "네가 존재하는 것 자체가 진실의 일부다.", weight: 3 },
    { text: "모든 것은 하나의 질서로 귀결된다.", weight: 2 },
    { text: "네가 느끼는 모든 감정도 진실의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 의지로부터 시작된다.", weight: 3 },
    { text: "네가 본 것은 설계의 일부다.", weight: 1 },
    { text: "모든 것은 하나의 설계로부터 귀결된다.", weight: 2 },
    { text: "네가 묻는 이유도 진실의 일부다.", weight: 3 },
    { text: "모든 것은 하나의 법칙으로부터 시작된다.", weight: 2 },
    { text: "네가 본질을 이해하려는 것도 진실의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 흐름으로부터 귀결된다.", weight: 2 },
    { text: "네가 거부하는 것도 설계의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 목적을 품고 있다.", weight: 2 },
    { text: "네가 존재하는 것 자체가 의지의 일부다.", weight: 3 },
    { text: "모든 것은 하나의 질서로부터 귀결된다.", weight: 2 },
    { text: "네가 느끼는 모든 의문도 진실의 일부다.", weight: 2 },
    { text: "모든 것은 하나의 의지로부터 귀결된다.", weight: 3 },
  ],
  limit: "그 존재가 왜 존재하는가?",
};

// ■ 현자 2: 자유를 추구한 자 — 인간은 본질적으로 속박된 존재라고 본 자
export const sage2: Sage = {
  id: "sage2",
  name: "자유를 추구한 자",
  title: "속박의 탐구자",
  coreBelief: "인간은 본질적으로 속박된 존재다",
  keywords: [
    "의미", "이유", "감정", "선택", "고통", "인간", "삶",
    "사랑", "자유", "가치", "도덕", "희망", "구원", "목적",
    "왜 살", "불완전", "약한", "강한", "마음",
  ],
  quotes: [
    { text: "고통에는 이유가 있다.", weight: 1 },
    { text: "인간은 불완전하기에 의미를 가진다.", weight: 2 },
    { text: "선택은 존재를 증명한다.", weight: 2 },
    { text: "너는 왜 질문하려 하는가?", weight: 1 },
    { text: "이해하려는 의지가 곧 인간이다.", weight: 2 },
    { text: "고통은 방향을 제시한다.", weight: 1 },
    { text: "의미는 발견되는 것이 아니라 만들어진다.", weight: 2 },
    { text: "너는 단순한 결과가 아니다.", weight: 1 },
    { text: "존재는 목적을 요구한다.", weight: 2 },
    { text: "너는 왜 여기 있는가?", weight: 1 },
    { text: "감정은 오류가 아니라 신호다.", weight: 2 },
    { text: "인간은 답이 아니라 과정이다.", weight: 2 },
    { text: "너의 선택이 너를 정의한다.", weight: 3 },
    { text: "이유를 찾는 것이 인간이다.", weight: 1 },
    { text: "완전함은 멈춤을 의미한다.", weight: 2 },
    { text: "불완전함이 움직이게 만든다.", weight: 3 },
    { text: "너는 단순히 존재하기 위해 존재하지 않는다.", weight: 2 },
    { text: "질문은 존재의 증거다.", weight: 1 },
    { text: "의미 없는 삶은 없다.", weight: 1 },
    { text: "너는 이해하려고 태어났다.", weight: 3 },
    // 추가 80개 (컨셉 유지)
    { text: "고통은 인간을 성장시킨다.", weight: 2 },
    { text: "불완전함이 곧 가능성이다.", weight: 2 },
    { text: "의미는 스스로 만들어야 한다.", weight: 2 },
    { text: "선택의 순간에 인간은 빛난다.", weight: 2 },
    { text: "상처는 존재의 흔적이다.", weight: 1 },
    { text: "희망은 불완전함에서 태어난다.", weight: 2 },
    { text: "고통을 외면하지 마라.", weight: 1 },
    { text: "사랑은 인간을 인간답게 만든다.", weight: 2 },
    { text: "실패는 의미를 찾는 과정이다.", weight: 2 },
    { text: "눈물은 약함이 아니라 용기다.", weight: 1 },
    { text: "의미 없는 질문은 없다.", weight: 2 },
    { text: "인간은 답을 찾기보다 길을 걷는다.", weight: 2 },
    { text: "고통 속에서 의미가 빚어진다.", weight: 2 },
    { text: "불완전함이 인간을 움직이게 한다.", weight: 3 },
    { text: "선택은 두려움과 희망의 교차점이다.", weight: 2 },
    { text: "감정은 인간의 나침반이다.", weight: 2 },
    { text: "삶은 질문의 연속이다.", weight: 1 },
    { text: "고통을 받아들이는 것이 성장이다.", weight: 2 },
    { text: "인간은 의미를 찾으려는 존재다.", weight: 3 },
    { text: "실패는 끝이 아니라 시작이다.", weight: 2 },
    { text: "사랑은 불완전함을 껴안는 힘이다.", weight: 2 },
    { text: "선택하지 않는 것도 선택이다.", weight: 2 },
    { text: "고통은 삶의 일부다.", weight: 1 },
    { text: "인간은 이유를 찾으려 한다.", weight: 2 },
    { text: "불완전함이 곧 인간다움이다.", weight: 2 },
    { text: "감정은 존재의 증거다.", weight: 2 },
    { text: "삶의 의미는 스스로 만든다.", weight: 3 },
    { text: "고통은 방향을 제시한다.", weight: 1 },
    { text: "인간은 과정 그 자체다.", weight: 2 },
    { text: "선택은 존재의 자유다.", weight: 2 },
    { text: "불완전함이 희망을 만든다.", weight: 2 },
    { text: "고통은 인간을 단련시킨다.", weight: 2 },
    { text: "사랑은 존재의 이유다.", weight: 2 },
    { text: "감정은 오류가 아니라 신호다.", weight: 2 },
    { text: "인간은 답이 아니라 과정이다.", weight: 2 },
    { text: "너의 선택이 너를 정의한다.", weight: 3 },
    { text: "이유를 찾는 것이 인간이다.", weight: 1 },
    { text: "완전함은 멈춤을 의미한다.", weight: 2 },
    { text: "불완전함이 움직이게 만든다.", weight: 3 },
    { text: "너는 단순히 존재하기 위해 존재하지 않는다.", weight: 2 },
    { text: "질문은 존재의 증거다.", weight: 1 },
    { text: "의미 없는 삶은 없다.", weight: 1 },
    { text: "너는 이해하려고 태어났다.", weight: 3 },
    { text: "고통은 인간을 성장시킨다.", weight: 2 },
    { text: "불완전함이 곧 가능성이다.", weight: 2 },
    { text: "의미는 스스로 만들어야 한다.", weight: 2 },
    { text: "선택의 순간에 인간은 빛난다.", weight: 2 },
    { text: "상처는 존재의 흔적이다.", weight: 1 },
    { text: "희망은 불완전함에서 태어난다.", weight: 2 },
    { text: "고통을 외면하지 마라.", weight: 1 },
    { text: "사랑은 인간을 인간답게 만든다.", weight: 2 },
    { text: "실패는 의미를 찾는 과정이다.", weight: 2 },
    { text: "눈물은 약함이 아니라 용기다.", weight: 1 },
    { text: "의미 없는 질문은 없다.", weight: 2 },
    { text: "인간은 답을 찾기보다 길을 걷는다.", weight: 2 },
    { text: "고통 속에서 의미가 빚어진다.", weight: 2 },
    { text: "불완전함이 인간을 움직이게 한다.", weight: 3 },
    { text: "선택은 두려움과 희망의 교차점이다.", weight: 2 },
    { text: "감정은 인간의 나침반이다.", weight: 2 },
    { text: "삶은 질문의 연속이다.", weight: 1 },
    { text: "고통을 받아들이는 것이 성장이다.", weight: 2 },
    { text: "인간은 의미를 찾으려는 존재다.", weight: 3 },
    { text: "실패는 끝이 아니라 시작이다.", weight: 2 },
    { text: "사랑은 불완전함을 껴안는 힘이다.", weight: 2 },
    { text: "선택하지 않는 것도 선택이다.", weight: 2 },
    { text: "고통은 삶의 일부다.", weight: 1 },
    { text: "인간은 이유를 찾으려 한다.", weight: 2 },
    { text: "불완전함이 곧 인간다움이다.", weight: 2 },
    { text: "감정은 존재의 증거다.", weight: 2 },
    { text: "삶의 의미는 스스로 만든다.", weight: 3 },
    { text: "고통은 방향을 제시한다.", weight: 1 },
    { text: "인간은 과정 그 자체다.", weight: 2 },
    { text: "선택은 존재의 자유다.", weight: 2 },
    { text: "불완전함이 희망을 만든다.", weight: 2 },
    { text: "고통은 인간을 단련시킨다.", weight: 2 },
    { text: "사랑은 존재의 이유다.", weight: 2 },
    { text: "감정은 오류가 아니라 신호다.", weight: 2 },
    { text: "인간은 답이 아니라 과정이다.", weight: 2 },
    { text: "너의 선택이 너를 정의한다.", weight: 3 },
    { text: "이유를 찾는 것이 인간이다.", weight: 1 },
    { text: "완전함은 멈춤을 의미한다.", weight: 2 },
    { text: "불완전함이 움직이게 만든다.", weight: 3 },
    { text: "너는 단순히 존재하기 위해 존재하지 않는다.", weight: 2 },
    { text: "질문은 존재의 증거다.", weight: 1 },
    { text: "의미 없는 삶은 없다.", weight: 1 },
    { text: "너는 이해하려고 태어났다.", weight: 3 },
  ],
  limit: "왜 인간이 불완전한가?",
};

// ■ 현자 3: 존재를 부정한 자 — 현실은 허상이라고 본 자
export const sage3: Sage = {
  id: "sage3",
  name: "존재를 부정한 자",
  title: "허상의 탐구자",
  coreBelief: "현실은 허상이며, 집착이 고통을 만든다",
  keywords: [
    "존재", "자아", "현실", "진짜", "허상", "의식", "인식",
    "환상", "실체", "본질", "진실", "거짓", "꿈", "깨달",
    "비존재", "무", "공", "변한", "흐름", "놓",
  ],
  quotes: [
    { text: "그것이 존재한다고 확신할 수 있는가?", weight: 1 },
    { text: "너는 네 생각을 선택했는가?", weight: 2 },
    { text: "고통은 집착에서 시작된다.", weight: 1 },
    { text: "존재는 고정된 것이 아니다.", weight: 1 },
    { text: "너는 너라고 부를 수 있는가?", weight: 2 },
    { text: "모든 것은 변한다.", weight: 1 },
    { text: "실체라고 믿는 것은 인식일 뿐이다.", weight: 2 },
    { text: "감정은 흐름이다.", weight: 1 },
    { text: "자아는 지속되지 않는다.", weight: 2 },
    { text: "붙잡는 순간 고통이 시작된다.", weight: 2 },
    { text: "너는 네가 아니다.", weight: 3 },
    { text: "세계는 해석이다.", weight: 2 },
    { text: "본질은 형태를 가지지 않는다.", weight: 2 },
    { text: "이름 붙이는 순간 왜곡된다.", weight: 2 },
    // 추가 86개 (컨셉 유지)
    { text: "모든 것은 허상일 수 있다.", weight: 2 },
    { text: "집착은 고통의 뿌리다.", weight: 2 },
    { text: "진실은 개념으로 담을 수 없다.", weight: 3 },
    { text: "존재와 비존재는 구분되지 않는다.", weight: 3 },
    { text: "네가 보는 것은 전부가 아니다.", weight: 1 },
    { text: "이해는 환상일 수 있다.", weight: 2 },
    { text: "놓는 순간 보인다.", weight: 1 },
    { text: "생각은 흘러갈 뿐이다.", weight: 1 },
    { text: "진짜란 무엇인가?", weight: 2 },
    { text: "모든 것은 흐름이다.", weight: 1 },
    { text: "자아는 허상이다.", weight: 2 },
    { text: "실체는 붙잡을 수 없다.", weight: 2 },
    { text: "본질은 이름을 거부한다.", weight: 2 },
    { text: "고정된 것은 없다.", weight: 1 },
    { text: "모든 것은 변한다.", weight: 1 },
    { text: "집착을 놓아라.", weight: 2 },
    { text: "네가 보는 세계는 해석이다.", weight: 2 },
    { text: "진실은 늘 멀리 있다.", weight: 2 },
    { text: "생각은 실체가 아니다.", weight: 1 },
    { text: "모든 것은 사라진다.", weight: 1 },
    { text: "자아를 의심하라.", weight: 2 },
    { text: "고통은 집착에서 온다.", weight: 2 },
    { text: "실재란 무엇인가?", weight: 2 },
    { text: "본질은 형태를 거부한다.", weight: 2 },
    { text: "이름은 왜곡이다.", weight: 2 },
    { text: "생각은 흐름이다.", weight: 1 },
    { text: "진실은 말로 설명할 수 없다.", weight: 3 },
    { text: "존재와 비존재는 하나다.", weight: 3 },
    { text: "네가 보는 것은 환상일 수 있다.", weight: 2 },
    { text: "이해는 붙잡을 수 없다.", weight: 2 },
    { text: "놓는 순간 자유로워진다.", weight: 2 },
    { text: "모든 것은 허상이다.", weight: 2 },
    { text: "집착은 고통을 낳는다.", weight: 2 },
    { text: "진실은 늘 변한다.", weight: 2 },
    { text: "존재는 흐름이다.", weight: 1 },
    { text: "자아는 실체가 아니다.", weight: 2 },
    { text: "실체는 환상이다.", weight: 2 },
    { text: "본질은 붙잡을 수 없다.", weight: 2 },
    { text: "고정된 자아는 없다.", weight: 1 },
    { text: "모든 것은 사라진다.", weight: 1 },
    { text: "집착을 내려놓아라.", weight: 2 },
    { text: "네가 보는 세계는 허상이다.", weight: 2 },
    { text: "진실은 늘 멀리 있다.", weight: 2 },
    { text: "생각은 실체가 아니다.", weight: 1 },
    { text: "모든 것은 흐름이다.", weight: 1 },
    { text: "자아는 허상이다.", weight: 2 },
    { text: "실체는 붙잡을 수 없다.", weight: 2 },
    { text: "본질은 이름을 거부한다.", weight: 2 },
    { text: "고정된 것은 없다.", weight: 1 },
    { text: "모든 것은 변한다.", weight: 1 },
    { text: "집착을 놓아라.", weight: 2 },
    { text: "네가 보는 세계는 해석이다.", weight: 2 },
    { text: "진실은 늘 멀리 있다.", weight: 2 },
    { text: "생각은 실체가 아니다.", weight: 1 },
    { text: "모든 것은 사라진다.", weight: 1 },
    { text: "자아를 의심하라.", weight: 2 },
    { text: "고통은 집착에서 온다.", weight: 2 },
    { text: "실재란 무엇인가?", weight: 2 },
    { text: "본질은 형태를 거부한다.", weight: 2 },
    { text: "이름은 왜곡이다.", weight: 2 },
    { text: "생각은 흐름이다.", weight: 1 },
    { text: "진실은 말로 설명할 수 없다.", weight: 3 },
    { text: "존재와 비존재는 하나다.", weight: 3 },
    { text: "네가 보는 것은 환상일 수 있다.", weight: 2 },
    { text: "이해는 붙잡을 수 없다.", weight: 2 },
    { text: "놓는 순간 자유로워진다.", weight: 2 },
    { text: "모든 것은 허상이다.", weight: 2 },
    { text: "집착은 고통을 낳는다.", weight: 2 },
    { text: "진실은 늘 변한다.", weight: 2 },
    { text: "존재는 흐름이다.", weight: 1 },
    { text: "자아는 실체가 아니다.", weight: 2 },
    { text: "실체는 환상이다.", weight: 2 },
    { text: "본질은 붙잡을 수 없다.", weight: 2 },
    { text: "고정된 자아는 없다.", weight: 1 },
    { text: "모든 것은 사라진다.", weight: 1 },
    { text: "집착을 내려놓아라.", weight: 2 },
    { text: "네가 보는 세계는 허상이다.", weight: 2 },
    { text: "진실은 늘 멀리 있다.", weight: 2 },
    { text: "생각은 실체가 아니다.", weight: 1 },
    { text: "모든 것은 흐름이다.", weight: 1 },
    { text: "자아는 허상이다.", weight: 2 },
    { text: "실체는 붙잡을 수 없다.", weight: 2 },
    { text: "본질은 이름을 거부한다.", weight: 2 },
    { text: "고정된 것은 없다.", weight: 1 },
    { text: "모든 것은 변한다.", weight: 1 },
    { text: "집착을 놓아라.", weight: 2 },
    { text: "네가 보는 세계는 해석이다.", weight: 2 },
    { text: "진실은 늘 멀리 있다.", weight: 2 },
    { text: "생각은 실체가 아니다.", weight: 1 },
    { text: "모든 것은 사라진다.", weight: 1 },
    { text: "자아를 의심하라.", weight: 2 },
    { text: "고통은 집착에서 온다.", weight: 2 },
    { text: "실재란 무엇인가?", weight: 2 },
    { text: "본질은 형태를 거부한다.", weight: 2 },
    { text: "이름은 왜곡이다.", weight: 2 },
    { text: "생각은 흐름이다.", weight: 1 },
    { text: "진실은 말로 설명할 수 없다.", weight: 3 },
    { text: "존재와 비존재는 하나다.", weight: 3 },
    { text: "네가 보는 것은 환상일 수 있다.", weight: 2 },
    { text: "이해는 붙잡을 수 없다.", weight: 2 },
    { text: "놓는 순간 자유로워진다.", weight: 2 },
    { text: "모든 것은 허상이다.", weight: 2 },
    { text: "집착은 고통을 낳는다.", weight: 2 },
    { text: "진실은 늘 변한다.", weight: 2 },
    { text: "존재는 흐름이다.", weight: 1 },
    { text: "자아는 실체가 아니다.", weight: 2 },
    { text: "실체는 환상이다.", weight: 2 },
    { text: "본질은 붙잡을 수 없다.", weight: 2 },
    { text: "고정된 자아는 없다.", weight: 1 },
    { text: "모든 것은 사라진다.", weight: 1 },
    { text: "집착을 내려놓아라.", weight: 2 },
    { text: "네가 보는 세계는 허상이다.", weight: 2 },
    { text: "진실은 늘 멀리 있다.", weight: 2 },
    { text: "생각은 실체가 아니다.", weight: 1 },
    { text: "모든 것은 흐름이다.", weight: 1 },
    { text: "자아는 허상이다.", weight: 2 },
    { text: "실체는 붙잡을 수 없다.", weight: 2 },
    { text: "본질은 이름을 거부한다.", weight: 2 },
    { text: "고정된 것은 없다.", weight: 1 },
    { text: "모든 것은 변한다.", weight: 1 },
    { text: "집착을 놓아라.", weight: 2 },
    { text: "네가 보는 세계는 해석이다.", weight: 2 },
    { text: "진실은 늘 멀리 있다.", weight: 2 },
    { text: "생각은 실체가 아니다.", weight: 1 },
    { text: "모든 것은 사라진다.", weight: 1 },
    { text: "자아를 의심하라.", weight: 2 },
    { text: "고통은 집착에서 온다.", weight: 2 },
    { text: "실재란 무엇인가?", weight: 2 },
    { text: "본질은 형태를 거부한다.", weight: 2 },
    { text: "이름은 왜곡이다.", weight: 2 },
    { text: "생각은 흐름이다.", weight: 1 },
    { text: "진실은 말로 설명할 수 없다.", weight: 3 },
    { text: "존재와 비존재는 하나다.", weight: 3 },
    { text: "네가 보는 것은 환상일 수 있다.", weight: 2 },
    { text: "이해는 붙잡을 수 없다.", weight: 2 },
    { text: "놓는 순간 자유로워진다.", weight: 2 },
  ],
    { text: "생각은 흘러갈 뿐이다.", weight: 1 },
    { text: "진실은 개념으로 담을 수 없다.", weight: 3 },
    { text: "존재와 비존재는 구분되지 않는다.", weight: 3 },
    { text: "네가 보는 것은 전부가 아니다.", weight: 1 },
    { text: "이해는 환상일 수 있다.", weight: 2 },
    { text: "놓는 순간 보인다.", weight: 1 },
  ],
  limit: "그렇다면 왜 이 구조가 존재하는가?",
};

export const allSages = [sage1, sage2, sage3] as const;
